import { Customer, MemoryItem, TimelineEvent, Ticket, AnalyticsData } from './types.js';

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91 98201 44812',
    device: 'iPhone 15',
    avatarColor: '#1e3a8a',
    preferences: ['Prefers email updates', 'Prefers card over netbanking', 'Morning contact hours'],
    totalInteractions: 14,
    lastInteraction: '18 Aug 2026',
    openTickets: 1,
    status: 'active',
    currentOrders: [
      {
        id: 'ORD-89412',
        productName: 'TechKart ProMax Smartphone 256GB',
        category: 'Smartphone',
        price: 899,
        date: '18 Aug 2026',
        status: 'Delivered',
      },
      {
        id: 'ORD-90145',
        productName: 'MagSafe Wireless Charging Pad',
        category: 'Accessories',
        price: 49,
        date: '24 Sep 2026',
        status: 'Processing',
      },
    ],
  },
  {
    id: 'CUST-002',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    phone: '+91 98490 22391',
    device: 'MacBook Pro M3',
    avatarColor: '#0f766e',
    preferences: ['Prefers detailed PDF invoices', 'Digital receipts only'],
    totalInteractions: 8,
    lastInteraction: '14 Sep 2026',
    openTickets: 0,
    status: 'resolved',
    currentOrders: [
      {
        id: 'ORD-87102',
        productName: 'TechKart UltraSound Over-Ear ANC Headphones',
        category: 'Audio',
        price: 299,
        date: '10 Sep 2026',
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'CUST-003',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@example.com',
    phone: '+91 97112 55670',
    device: 'Google Pixel 8 Pro',
    avatarColor: '#b45309',
    preferences: ['WhatsApp notifications', 'Beta firmware updates permitted'],
    totalInteractions: 11,
    lastInteraction: '04 Sep 2026',
    openTickets: 0,
    status: 'resolved',
    currentOrders: [
      {
        id: 'ORD-85401',
        productName: 'SonicBuds Pro True Wireless Earbuds',
        category: 'Earbuds',
        price: 159,
        date: '28 Aug 2026',
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'CUST-004',
    name: 'Priya Kapoor',
    email: 'priya.kapoor@example.com',
    phone: '+91 98109 66782',
    device: 'Samsung Galaxy S24',
    avatarColor: '#4338ca',
    preferences: ['Delivery time slot 09:00 - 12:00', 'Leave with building security if unavailable'],
    totalInteractions: 9,
    lastInteraction: '21 Sep 2026',
    openTickets: 1,
    status: 'active',
    currentOrders: [
      {
        id: 'ORD-91024',
        productName: 'PulseActive Smartwatch Fit 2',
        category: 'Smartwatches',
        price: 199,
        date: '19 Sep 2026',
        status: 'In Transit',
      },
    ],
  },
  {
    id: 'CUST-005',
    name: 'Karthik Rao',
    email: 'karthik.rao@example.com',
    phone: '+91 99001 77890',
    device: 'Windows 11 Custom PC',
    avatarColor: '#0369a1',
    preferences: ['Requires GST corporate invoice', 'Extended 3-year warranty package holder'],
    totalInteractions: 16,
    lastInteraction: '12 Sep 2026',
    openTickets: 0,
    status: 'resolved',
    currentOrders: [
      {
        id: 'ORD-82194',
        productName: 'Apex Titan Gaming Laptop RTX 4080 32GB',
        category: 'Laptops',
        price: 2199,
        date: '02 Sep 2026',
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'CUST-006',
    name: 'Ananya Singh',
    email: 'ananya.singh@example.com',
    phone: '+91 98765 11234',
    device: 'iPad Pro 12.9',
    avatarColor: '#374151',
    preferences: ['Express return pickup service', 'Notification via SMS and Email'],
    totalInteractions: 6,
    lastInteraction: '09 Sep 2026',
    openTickets: 1,
    status: 'pending',
    currentOrders: [
      {
        id: 'ORD-88712',
        productName: 'ThunderDock 10-in-1 USB-C Multiport Hub',
        category: 'Accessories',
        price: 89,
        date: '05 Sep 2026',
        status: 'Delivered',
      },
    ],
  },
];

export const SEED_MEMORIES: MemoryItem[] = [
  // Rahul Sharma (CUST-001) Hero Scenario Memories
  {
    id: 'MEM-001',
    customerId: 'CUST-001',
    namespace: 'customer_CUST_001',
    category: 'payment',
    title: 'UPI Payment Failure and Card Resolution',
    summary: 'Customer experienced UPI gateway timeout during checkout. Support recommended card payment, which processed successfully without latency.',
    solution: 'Switched from UPI to Visa/Mastercard credit/debit card payment. Gateway authorized immediately.',
    outcome: 'Successful payment authorization and order placement.',
    device: 'iPhone 15',
    timestamp: '2026-08-18T14:32:00Z',
    dateDisplay: '18 Aug 2026',
    tags: ['upi', 'payment', 'timeout', 'card', 'checkout', 'gateway failure'],
    importance: 0.95,
    recalledCount: 3,
  },
  {
    id: 'MEM-002',
    customerId: 'CUST-001',
    namespace: 'customer_CUST_001',
    category: 'order',
    title: 'Accidental Duplicate Order Cancellation',
    summary: 'Customer mistakenly initiated dual orders for the same smartphone model due to connection lag.',
    solution: 'Processed instant cancellation on duplicate order ORD-89411 before warehouse dispatch.',
    outcome: 'Zero fee cancellation processed; customer satisfied.',
    device: 'iPhone 15',
    timestamp: '2026-07-03T10:15:00Z',
    dateDisplay: '03 Jul 2026',
    tags: ['cancellation', 'duplicate order', 'dispatch', 'refund'],
    importance: 0.75,
    recalledCount: 1,
  },
  {
    id: 'MEM-003',
    customerId: 'CUST-001',
    namespace: 'customer_CUST_001',
    category: 'delivery',
    title: 'Courier Delayed Delivery Handshake',
    summary: 'Monsoon weather caused 48-hour delivery delay in Mumbai suburban zone.',
    solution: 'Coordinated direct priority dispatch via BlueDart express line.',
    outcome: 'Delivered safely with real-time SMS tracking updates.',
    device: 'iPhone 15',
    timestamp: '2026-06-12T16:40:00Z',
    dateDisplay: '12 Jun 2026',
    tags: ['delivery delay', 'courier', 'mumbai', 'logistics', 'tracking'],
    importance: 0.7,
    recalledCount: 1,
  },
  {
    id: 'MEM-004',
    customerId: 'CUST-001',
    namespace: 'customer_CUST_001',
    category: 'preference',
    title: 'Notification and Contact Preference',
    summary: 'Customer prefers written email documentation over unannounced voice phone calls.',
    solution: 'Set account dispatch preferences to email and in-app messages.',
    outcome: 'Communication profile updated.',
    device: 'iPhone 15',
    timestamp: '2026-06-12T17:00:00Z',
    dateDisplay: '12 Jun 2026',
    tags: ['preference', 'email', 'contact protocol'],
    importance: 0.8,
    recalledCount: 4,
  },

  // Sneha Reddy (CUST-002)
  {
    id: 'MEM-005',
    customerId: 'CUST-002',
    namespace: 'customer_CUST_002',
    category: 'account',
    title: 'GST Business Invoice Generation Requirement',
    summary: 'Customer requires specific GSTIN tax registration details embedded into all electronic equipment invoices.',
    solution: 'Saved verified GSTIN to customer billing vault.',
    outcome: 'All consecutive order invoices automatically generate compliant tax receipts.',
    device: 'MacBook Pro M3',
    timestamp: '2026-09-14T11:20:00Z',
    dateDisplay: '14 Sep 2026',
    tags: ['invoice', 'gst', 'tax receipt', 'billing'],
    importance: 0.85,
    recalledCount: 2,
  },

  // Arjun Mehta (CUST-003)
  {
    id: 'MEM-006',
    customerId: 'CUST-003',
    namespace: 'customer_CUST_003',
    category: 'technical',
    title: 'SonicBuds Pro Left Channel Audio Sync',
    summary: 'Customer reported left earbud disconnected after pairing with secondary laptop.',
    solution: 'Guided through 10-second factory pin reset and firmware upgrade to v2.1 via TechKart Audio companion tool.',
    outcome: 'Stereo sync restored, zero latency confirmed.',
    device: 'Google Pixel 8 Pro',
    timestamp: '2026-09-04T09:45:00Z',
    dateDisplay: '04 Sep 2026',
    tags: ['audio', 'earbuds', 'firmware', 'bluetooth', 'reset'],
    importance: 0.9,
    recalledCount: 2,
  },

  // Priya Kapoor (CUST-004)
  {
    id: 'MEM-007',
    customerId: 'CUST-004',
    namespace: 'customer_CUST_004',
    category: 'delivery',
    title: 'Pincode Address Correction and Morning Delivery Slot',
    summary: 'Delivery courier failed initial delivery attempt due to gated community access restriction before 10 AM.',
    solution: 'Updated courier route notes with building guard gate permission and designated 10:00 - 12:00 morning delivery window.',
    outcome: 'Delivery succeeded smoothly on next cycle.',
    device: 'Samsung Galaxy S24',
    timestamp: '2026-09-21T08:30:00Z',
    dateDisplay: '21 Sep 2026',
    tags: ['delivery', 'pincode', 'gated community', 'morning schedule'],
    importance: 0.88,
    recalledCount: 2,
  },

  // Karthik Rao (CUST-005)
  {
    id: 'MEM-008',
    customerId: 'CUST-005',
    namespace: 'customer_CUST_005',
    category: 'technical',
    title: 'Apex Titan Laptop GPU Driver Thermal Profile',
    summary: 'Customer experienced high fan noise during CAD render benchmarks.',
    solution: 'Advised switching thermal throttle mode from Performance Extreme to Studio Dynamic via UEFI management.',
    outcome: 'Temperatures dropped 14 degrees Celsius with stable render performance.',
    device: 'Windows 11 Custom PC',
    timestamp: '2026-09-12T15:10:00Z',
    dateDisplay: '12 Sep 2026',
    tags: ['gpu', 'thermal', 'laptop', 'fan noise', 'uefi'],
    importance: 0.85,
    recalledCount: 1,
  },

  // Ananya Singh (CUST-006)
  {
    id: 'MEM-009',
    customerId: 'CUST-006',
    namespace: 'customer_CUST_006',
    category: 'return',
    title: 'USB-C Docking Station Video Output Defect',
    summary: 'Customer encountered flickering HDMI output when connecting external 4K monitor.',
    solution: 'Verified hardware HDMI port solder issue, initiated reverse pickup with immediate advance replacement shipment.',
    outcome: 'Replacement unit tested and shipped via express courier.',
    device: 'iPad Pro 12.9',
    timestamp: '2026-09-09T13:00:00Z',
    dateDisplay: '09 Sep 2026',
    tags: ['return', 'docking station', 'hdmi', 'replacement', 'defect'],
    importance: 0.88,
    recalledCount: 1,
  },
];

export const SEED_TIMELINE: TimelineEvent[] = [
  {
    id: 'TL-001',
    customerId: 'CUST-001',
    date: '2026-06-12',
    issue: 'Delivery Delay on Monsoon Route',
    diagnosis: 'Regional monsoon road closure affected transit from central distribution warehouse',
    suggestedAction: 'Rerouted through secondary air freight hub with express notification',
    outcome: 'Package safely delivered in 48 hours',
    memoryRefId: 'MEM-003',
  },
  {
    id: 'TL-002',
    customerId: 'CUST-001',
    date: '2026-07-03',
    issue: 'Duplicate Order Cancellation',
    diagnosis: 'Checkout button tapped twice during mobile network handoff',
    suggestedAction: 'Immediate automated cancellation and pre-authorization void',
    outcome: 'Zero charge incurred; single order retained',
    memoryRefId: 'MEM-002',
  },
  {
    id: 'TL-003',
    customerId: 'CUST-001',
    date: '2026-08-18',
    issue: 'Payment Failure on UPI Gateway',
    diagnosis: 'UPI banking server timed out after 180 seconds during festival rush',
    suggestedAction: 'Advised customer to switch to Visa/Mastercard card payment route',
    outcome: 'Payment confirmed in 4 seconds; order ORD-89412 fulfilled',
    memoryRefId: 'MEM-001',
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'TK-1042',
    customerId: 'CUST-001',
    customerName: 'Rahul Sharma',
    issue: 'Repeated UPI payment gateway timeout during checkout',
    category: 'Payment',
    previousOccurrences: 2,
    knownPattern: 'UPI server timeout during peak traffic hours',
    previousSuccessfulSolution: 'Switch to credit/debit card payment gateway',
    currentStatus: 'Unresolved',
    priority: 'Medium',
    createdAt: '2026-09-27T08:15:00Z',
    device: 'iPhone 15',
  },
  {
    id: 'TK-1038',
    customerId: 'CUST-004',
    customerName: 'Priya Kapoor',
    issue: 'Morning delivery access instruction synchronization',
    category: 'Delivery',
    previousOccurrences: 1,
    knownPattern: 'Gated community requires security desk dispatch clearance',
    previousSuccessfulSolution: 'Designated 10:00 - 12:00 slot with security clearance code',
    currentStatus: 'Unresolved',
    priority: 'Low',
    createdAt: '2026-09-26T11:30:00Z',
    device: 'Samsung Galaxy S24',
  },
  {
    id: 'TK-1031',
    customerId: 'CUST-006',
    customerName: 'Ananya Singh',
    issue: 'ThunderDock 10-in-1 HDMI display port signal degradation',
    category: 'Product',
    previousOccurrences: 1,
    knownPattern: 'Hardware HDMI signal intermittent failure on batch 404',
    previousSuccessfulSolution: 'Advance replacement dispatch with prepaid return label',
    currentStatus: 'Unresolved',
    priority: 'High',
    createdAt: '2026-09-25T14:20:00Z',
    device: 'iPad Pro 12.9',
  },
  {
    id: 'TK-1019',
    customerId: 'CUST-003',
    customerName: 'Arjun Mehta',
    issue: 'Earbud channel desynchronization after multi-device pairing',
    category: 'Technical Issue',
    previousOccurrences: 1,
    knownPattern: 'Bluetooth LE audio profile collision across macOS and Android',
    previousSuccessfulSolution: 'Factory hard reset and firmware update v2.1',
    currentStatus: 'Resolved',
    priority: 'Low',
    createdAt: '2026-09-04T10:00:00Z',
    device: 'Google Pixel 8 Pro',
  },
];

export const INITIAL_ANALYTICS: AnalyticsData = {
  totalCustomers: 1248,
  totalConversations: 4930,
  memoriesStored: 7412,
  problemsResolved: 4520,
  repeatedIssuesDetected: 894,
  avgResolutionTimeMinutes: 3.2,
  memoryUtilizationRate: 78.4,
  issuesByCategory: [
    { category: 'Payment', count: 1480, percentage: 32 },
    { category: 'Delivery', count: 1120, percentage: 25 },
    { category: 'Product & Tech', count: 910, percentage: 20 },
    { category: 'Return & Refund', count: 680, percentage: 15 },
    { category: 'Account & Billing', count: 360, percentage: 8 },
  ],
  resolutionTrend: [
    { month: 'Apr', genericAvgMin: 14.5, memoryAvgMin: 7.8 },
    { month: 'May', genericAvgMin: 14.2, memoryAvgMin: 6.4 },
    { month: 'Jun', genericAvgMin: 13.9, memoryAvgMin: 5.1 },
    { month: 'Jul', genericAvgMin: 14.1, memoryAvgMin: 4.3 },
    { month: 'Aug', genericAvgMin: 13.8, memoryAvgMin: 3.6 },
    { month: 'Sep', genericAvgMin: 13.7, memoryAvgMin: 3.2 },
  ],
};
